STAF-35: add slide in menu from the sides
devmc-ee/shifts-manager pull request #55
Opened 2023-03-05 11:21 UTC by RomanLavrunov

2023-03-07 17:38 UTC, devmc-ee requested changes

2023-03-10 19:58 UTC, RomanLavrunov commented on src/core/components/SlideInProvider/SlideInProvider.tsx
> +  const title = slideFrom === 'left' ? 'Menu' : 'Profile';
fixed

2023-03-12 11:01 UTC, devmc-ee requested changes

2023-03-12 21:35 UTC, RomanLavrunov commented on src/config/slideInMenuConfig.ts
> +export type MenuBlockType = {
Name changed.

2023-03-12 21:35 UTC, RomanLavrunov commented on src/core/components/Menus/MenuItemList/MenuItemList.tsx
> +            <span className="menu-list-item-title">{`${t(`core.slideInBar.${componentName}.${item.id}`)}`}</span>
Comment added!

2023-03-12 21:35 UTC, RomanLavrunov commented on src/assets/theme/_variables.scss
> +  bp-1400: 1400,
Fixed!

2023-03-13 15:36 UTC, devmc-ee approved these changes

2023-03-13 15:37 UTC, merged